var searchData=
[
  ['data_0',['data',['../unionicalvalue__impl_1_1data.html',1,'icalvalue_impl::data'],['../unionvcardvalue__impl_1_1data.html',1,'vcardvalue_impl::data']]],
  ['data_20formats_1',['data formats',['../index.html',1,'Libical — an implementation of iCalendar protocols and data formats'],['..//home/winterz/projects/libical/libical/docs/README.md#autotoc_md152',1,'Libical — an implementation of iCalendar protocols and data formats']]],
  ['data_20types_2',['data types',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md134',1,'Added data types'],['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md135',1,'Removed data types']]],
  ['date_20time_20section_203_203_205_3',['DATE-TIME section 3.3.5',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2KnownExceptions.html#autotoc_md120',1,'']]],
  ['day_4',['day',['../structut__instant__int.html#a1676843b5827300c9eb4dba6dce8dfba',1,'ut_instant_int']]],
  ['day_5fof_5fyear_5',['day_of_year',['../structut__instant__int.html#a2a672639c1668aa98a3f3e10c55e7026',1,'ut_instant_int']]],
  ['dbtype_6',['dbtype',['../structicalbdbset__options.html#a3c5ba0f36190405b6424f3a4b9c30f62',1,'icalbdbset_options']]],
  ['dependencies_7',['Dependencies',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2Dependencies.html',1,'Dependencies'],['../md__2home_2winterz_2projects_2libical_2libical_2INSTALL.html#autotoc_md43',1,'Optional Dependencies'],['../md__2home_2winterz_2projects_2libical_2libical_2docs_2INSTALL.html#autotoc_md107',1,'Optional Dependencies']]],
  ['dependencies_8',['dependencies',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2Dependencies.html#autotoc_md101',1,'Optional dependencies'],['../md__2home_2winterz_2projects_2libical_2libical_2INSTALL.html#autotoc_md48',1,'Using vcpkg to install dependencies'],['../md__2home_2winterz_2projects_2libical_2libical_2docs_2INSTALL.html#autotoc_md112',1,'Using vcpkg to install dependencies']]],
  ['deprecated_9',['Deprecated',['../md__2home_2winterz_2projects_2libical_2libical_2CHANGELOG.html#autotoc_md9',1,'Deprecated'],['../md__2home_2winterz_2projects_2libical_2libical_2docs_2CHANGELOG.html#autotoc_md68',1,'Deprecated']]],
  ['differences_20from_20rfcs_10',['4 Differences From RFCs',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2UsingLibical.html#autotoc_md179',1,'']]],
  ['different_20compilers_11',['Different Compilers',['../md__2home_2winterz_2projects_2libical_2libical_2INSTALL.html#autotoc_md39',1,'Building with Different Compilers'],['../md__2home_2winterz_2projects_2libical_2libical_2docs_2INSTALL.html#autotoc_md103',1,'Building with Different Compilers']]],
  ['dir_12',['dir',['../structicaldirset__impl.html#a6fc97201a8df517a5955e1ab1e7f2a68',1,'icaldirset_impl']]],
  ['directories_13',['Directories',['../md__2home_2winterz_2projects_2libical_2libical_2INSTALL.html#autotoc_md46',1,'Tweaking the Installation Directories'],['../md__2home_2winterz_2projects_2libical_2libical_2docs_2INSTALL.html#autotoc_md110',1,'Tweaking the Installation Directories']]],
  ['directory_14',['directory',['../structicaldirset__impl.html#aa305d137f8cf5337c90c9b1cb14a5935',1,'icaldirset_impl']]],
  ['directory_5fiterator_15',['directory_iterator',['../structicaldirset__impl.html#a29fdec1fc0977685811c5991c104fa39',1,'icaldirset_impl']]],
  ['do_20journal_20free_20busy_20component_20section_203_206_201_204_16',['Event/To-Do/Journal/Free-Busy Component section 3.6.[1-4]',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2KnownExceptions.html#autotoc_md118',1,'']]],
  ['documentation_17',['Documentation',['../index.html#autotoc_md56',1,'Documentation'],['..//home/winterz/projects/libical/libical/docs/README.md#autotoc_md157',1,'Documentation']]],
  ['documentation_18',['documentation',['../md__2home_2winterz_2projects_2libical_2libical_2INSTALL.html#autotoc_md47',1,'Build the documentation'],['../md__2home_2winterz_2projects_2libical_2libical_2docs_2INSTALL.html#autotoc_md111',1,'Build the documentation']]],
  ['doubles_19',['&lt;span class=&quot;tt&quot;&gt;icalgeotype&lt;/span&gt; now uses character strings rather than doubles',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md141',1,'']]],
  ['doxygen_20awesome_20',['Doxygen Awesome',['../md__2home_2winterz_2projects_2libical_2libical_23RDPARTY.html#autotoc_md4',1,'Doxygen Awesome'],['../md__2home_2winterz_2projects_2libical_2libical_2docs_23RDPARTY.html#autotoc_md63',1,'Doxygen Awesome']]],
  ['dynamically_20allocated_20ones_21',['&lt;span class=&quot;tt&quot;&gt;icalrecurrencetype.by_xxx&lt;/span&gt; static arrays replaced by dynamically allocated ones',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md148',1,'']]]
];
