var searchData=
[
  ['a_20new_20set_0',['5.4.1 Creating a new set',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2UsingLibical.html#autotoc_md201',1,'']]],
  ['about_1',['About',['../index.html#autotoc_md52',1,'About'],['..//home/winterz/projects/libical/libical/docs/README.md#autotoc_md153',1,'About']]],
  ['accessing_20components_2',['5.2 Accessing Components',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2UsingLibical.html#autotoc_md188',1,'']]],
  ['acknowledgments_3',['Acknowledgments',['../index.html#autotoc_md57',1,'Acknowledgments'],['..//home/winterz/projects/libical/libical/docs/README.md#autotoc_md158',1,'Acknowledgments']]],
  ['added_4',['Added',['../md__2home_2winterz_2projects_2libical_2libical_2CHANGELOG.html#autotoc_md7',1,'Added'],['../md__2home_2winterz_2projects_2libical_2libical_2docs_2CHANGELOG.html#autotoc_md66',1,'Added']]],
  ['added_20data_20types_5',['Added data types',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md134',1,'']]],
  ['adding_20finding_20and_20removing_20components_6',['5.4.2 Adding, Finding and Removing Components',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2UsingLibical.html#autotoc_md202',1,'']]],
  ['allocated_20ones_7',['&lt;span class=&quot;tt&quot;&gt;icalrecurrencetype.by_xxx&lt;/span&gt; static arrays replaced by dynamically allocated ones',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md148',1,'']]],
  ['an_20implementation_20of_20icalendar_20protocols_20and_20data_20formats_8',['an implementation of iCalendar protocols and data formats',['../index.html',1,'Libical — an implementation of iCalendar protocols and data formats'],['..//home/winterz/projects/libical/libical/docs/README.md#autotoc_md152',1,'Libical — an implementation of iCalendar protocols and data formats']]],
  ['and_20bugs_9',['6 Hacks and Bugs',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2UsingLibical.html#autotoc_md211',1,'']]],
  ['and_20data_20formats_10',['and data formats',['../index.html',1,'Libical — an implementation of iCalendar protocols and data formats'],['..//home/winterz/projects/libical/libical/docs/README.md#autotoc_md152',1,'Libical — an implementation of iCalendar protocols and data formats']]],
  ['and_20ical_5fboolean_5ffalse_11',['ICAL_BOOLEAN_TRUE and ICAL_BOOLEAN_FALSE',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md128',1,'']]],
  ['and_20icalerror_5ferrors_5fare_5ffatal_12',['5.6.4 &lt;span class=&quot;tt&quot;&gt;LIBICAL_ENABLE_ERRORS_ARE_FATAL&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;icalerror_errors_are_fatal&lt;/span&gt;',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2UsingLibical.html#autotoc_md209',1,'']]],
  ['and_20icalproperty_13',['Working with &lt;span class=&quot;tt&quot;&gt;icalvalue&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;icalproperty&lt;/span&gt;',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md143',1,'']]],
  ['and_20parameters_14',['5.2.5 Working with properties and parameters',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2UsingLibical.html#autotoc_md193',1,'']]],
  ['and_20removing_20components_15',['5.4.2 Adding, Finding and Removing Components',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2UsingLibical.html#autotoc_md202',1,'']]],
  ['and_20types_16',['3.2.1 Enumerations and types',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2UsingLibical.html#autotoc_md174',1,'']]],
  ['and_20x_20lic_20invalid_20component_17',['5.6.3 &lt;span class=&quot;tt&quot;&gt;X-LIC-ERROR&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;X-LIC-INVALID-COMPONENT&lt;/span&gt;',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2UsingLibical.html#autotoc_md208',1,'']]],
  ['android_18',['Android',['../md__2home_2winterz_2projects_2libical_2libical_2INSTALL.html#autotoc_md42',1,'Building for Android'],['../md__2home_2winterz_2projects_2libical_2libical_2docs_2INSTALL.html#autotoc_md106',1,'Building for Android']]],
  ['arrays_20replaced_20by_20dynamically_20allocated_20ones_19',['&lt;span class=&quot;tt&quot;&gt;icalrecurrencetype.by_xxx&lt;/span&gt; static arrays replaced by dynamically allocated ones',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md148',1,'']]],
  ['arrays_20usage_20from_203_200_20to_204_200_20',['Migrating &lt;span class=&quot;tt&quot;&gt;icalrecurrencetype.by_xxx&lt;/span&gt; static arrays usage from 3.0 to 4.0',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md149',1,'']]],
  ['awesome_21',['Awesome',['../md__2home_2winterz_2projects_2libical_2libical_23RDPARTY.html#autotoc_md4',1,'Doxygen Awesome'],['../md__2home_2winterz_2projects_2libical_2libical_2docs_23RDPARTY.html#autotoc_md63',1,'Doxygen Awesome']]]
];
