var searchData=
[
  ['ical_20classes_0',['3.1 Core iCal classes',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2UsingLibical.html#autotoc_md112',1,'']]],
  ['ical_5fallow_5fempty_5fproperties_1',['ICAL_ALLOW_EMPTY_PROPERTIES',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md69',1,'']]],
  ['ical_5fboolean_5ffalse_2',['ICAL_BOOLEAN_TRUE and ICAL_BOOLEAN_FALSE',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md72',1,'']]],
  ['ical_5fboolean_5ftrue_20and_20ical_5fboolean_5ffalse_3',['ICAL_BOOLEAN_TRUE and ICAL_BOOLEAN_FALSE',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md72',1,'']]],
  ['ical_5fenable_5ferrors_5fare_5ffatal_4',['ICAL_ENABLE_ERRORS_ARE_FATAL',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md68',1,'']]],
  ['ical_5fseterror_5fisfunc_5',['ICAL_SETERROR_ISFUNC',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md71',1,'']]],
  ['icalendar_20protocols_20and_20data_20formats_6',['Libical — an implementation of iCalendar protocols and data formats',['../index.html',1,'']]],
  ['icalerror_5ferrors_5fare_5ffatal_7',['5.6.4 &lt;span class=&quot;tt&quot;&gt;LIBICAL_ENABLE_ERRORS_ARE_FATAL&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;icalerror_errors_are_fatal&lt;/span&gt;',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2UsingLibical.html#autotoc_md153',1,'']]],
  ['icalgeotype_20now_20uses_20character_20strings_20rather_20than_20doubles_8',['&lt;span class=&quot;tt&quot;&gt;icalgeotype&lt;/span&gt; now uses character strings rather than doubles',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md85',1,'']]],
  ['icalglib_20recurrence_20_5fby_5f_20methods_9',['GLib/Python bindings - changed &lt;span class=&quot;tt&quot;&gt;ICalGLib.Recurrence.*_by_*&lt;/span&gt; methods',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md94',1,'']]],
  ['icalglib_20recurrence_20_5fby_5f_20methods_20from_203_200_20to_204_200_10',['Migrating &lt;span class=&quot;tt&quot;&gt;ICalGLib.Recurrence.*_by_*&lt;/span&gt; methods from 3.0 to 4.0',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md95',1,'']]],
  ['icalproperty_11',['Working with &lt;span class=&quot;tt&quot;&gt;icalvalue&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;icalproperty&lt;/span&gt;',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md87',1,'']]],
  ['icalrecurrencetype_20by_5fxxx_20static_20arrays_20replaced_20by_20dynamically_20allocated_20ones_12',['&lt;span class=&quot;tt&quot;&gt;icalrecurrencetype.by_xxx&lt;/span&gt; static arrays replaced by dynamically allocated ones',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md92',1,'']]],
  ['icalrecurrencetype_20by_5fxxx_20static_20arrays_20usage_20from_203_200_20to_204_200_13',['Migrating &lt;span class=&quot;tt&quot;&gt;icalrecurrencetype.by_xxx&lt;/span&gt; static arrays usage from 3.0 to 4.0',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md93',1,'']]],
  ['icalrecurrencetype_20now_20passed_20by_20reference_14',['&lt;span class=&quot;tt&quot;&gt;icalrecurrencetype&lt;/span&gt; now passed by reference',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md84',1,'']]],
  ['icaltime_5fadjust_15',['icaltime_adjust',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md86',1,'']]],
  ['icaltimetype_16',['icaltimetype',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2UsingLibical.html#autotoc_md157',1,'7.1 Manipulating struct icaltimetype'],['../md__2home_2winterz_2projects_2libical_2libical_2docs_2UsingLibical.html#autotoc_md158',1,'7.1.1 Struct icaltimetype']]],
  ['icalvalue_20and_20icalproperty_17',['Working with &lt;span class=&quot;tt&quot;&gt;icalvalue&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;icalproperty&lt;/span&gt;',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md87',1,'']]],
  ['implementation_20of_20icalendar_20protocols_20and_20data_20formats_18',['Libical — an implementation of iCalendar protocols and data formats',['../index.html',1,'']]],
  ['install_20dependencies_19',['Using vcpkg to install dependencies',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2INSTALL.html#autotoc_md56',1,'']]],
  ['installation_20directories_20',['Tweaking the Installation Directories',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2INSTALL.html#autotoc_md54',1,'']]],
  ['interfaces_21',['5.1.1 Constructor Interfaces',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2UsingLibical.html#autotoc_md129',1,'']]],
  ['internal_20limits_22',['Internal Limits',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2InternalLimits.html',1,'']]],
  ['introduction_23',['1 Introduction',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2UsingLibical.html#autotoc_md106',1,'']]],
  ['invalid_20component_24',['5.6.3 &lt;span class=&quot;tt&quot;&gt;X-LIC-ERROR&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;X-LIC-INVALID-COMPONENT&lt;/span&gt;',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2UsingLibical.html#autotoc_md152',1,'']]],
  ['involved_25',['Get Involved',['../index.html#autotoc_md104',1,'']]],
  ['iterating_20through_20components_26',['5.2.2 Iterating Through Components',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2UsingLibical.html#autotoc_md134',1,'']]],
  ['iterators_27',['5.2.3 Using Component Iterators',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2UsingLibical.html#autotoc_md135',1,'']]]
];
