var searchData=
[
  ['files_0',['5.1.3 Parsing Text Files',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2UsingLibical.html#autotoc_md187',1,'']]],
  ['finding_20and_20removing_20components_1',['5.4.2 Adding, Finding and Removing Components',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2UsingLibical.html#autotoc_md202',1,'']]],
  ['finding_20components_2',['5.2.1 Finding Components',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2UsingLibical.html#autotoc_md189',1,'']]],
  ['fixed_3',['Fixed',['../md__2home_2winterz_2projects_2libical_2libical_2CHANGELOG.html#autotoc_md11',1,'Fixed'],['../md__2home_2winterz_2projects_2libical_2libical_2docs_2CHANGELOG.html#autotoc_md70',1,'Fixed']]],
  ['for_20android_4',['for Android',['../md__2home_2winterz_2projects_2libical_2libical_2INSTALL.html#autotoc_md42',1,'Building for Android'],['../md__2home_2winterz_2projects_2libical_2libical_2docs_2INSTALL.html#autotoc_md106',1,'Building for Android']]],
  ['for_20osx_20mac_5',['for OSX Mac',['../md__2home_2winterz_2projects_2libical_2libical_2INSTALL.html#autotoc_md40',1,'Building for OSX (Mac)'],['../md__2home_2winterz_2projects_2libical_2libical_2docs_2INSTALL.html#autotoc_md104',1,'Building for OSX (Mac)']]],
  ['formats_6',['formats',['../index.html',1,'Libical — an implementation of iCalendar protocols and data formats'],['..//home/winterz/projects/libical/libical/docs/README.md#autotoc_md152',1,'Libical — an implementation of iCalendar protocols and data formats']]],
  ['free_20busy_20component_20section_203_206_201_204_7',['Event/To-Do/Journal/Free-Busy Component section 3.6.[1-4]',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2KnownExceptions.html#autotoc_md118',1,'']]],
  ['from_203_200_20to_204_200_8',['from 3 0 to 4 0',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md151',1,'Migrating <span class="tt">ICalGLib.Recurrence.*_by_*</span> methods from 3.0 to 4.0'],['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md149',1,'Migrating <span class="tt">icalrecurrencetype.by_xxx</span> static arrays usage from 3.0 to 4.0'],['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md136',1,'Migrating from 3.0 to 4.0']]],
  ['from_20rfcs_9',['4 Differences From RFCs',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2UsingLibical.html#autotoc_md179',1,'']]],
  ['functions_10',['functions',['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md139',1,'Clone functions'],['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md130',1,'Modified functions'],['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md131',1,'New functions'],['../md__2home_2winterz_2projects_2libical_2libical_2docs_2MigrationGuide__to__4.html#autotoc_md132',1,'Removed functions']]]
];
