@echo off

REM SPDX-FileCopyrightText: Allen Winter <winter@kde.org>
REM SPDX-License-Identifier: LGPL-2.1-only OR MPL-2.0

set CMAKE_VERSION4_OPTIONS=-DLIBICAL_DEVMODE=ON -DLIBICAL_DEVMODE_MEMORY_CONSISTENCY=ON -DLIBICAL_DEVMODE_SYNCMODE_THREADLOCAL=ON -DLIBICAL_BUILD_VZIC=OFF

set BDIR=build-foo
rmdir %BDIR% /s /q
mkdir %BDIR%
cd %BDIR%

cmake -S  .. -G Ninja -DCMAKE_BUILD_TYPE=Debug -DLIBICAL_STATIC=OFF -DLIBICAL_ENABLE_BUILTIN_TZDATA=ON -DLIBICAL_BUILD_TESTING=ON -DLIBICAL_BUILD_DOCS=ON -DLIBICAL_BUILD_EXAMPLES=ON -DLIBICAL_CXX_BINDINGS=ON -DLIBICAL_JAVA_BINDINGS=OFF -DLIBICAL_GLIB=OFF -DLIBICAL_GOBJECT_INTROSPECTION=OFF -DLIBICAL_GLIB_VAPI=OFF -DLIBICAL_GLIB_BUILD_DOCS=OFF %CMAKE_VERSION4_OPTIONS% -DLIBICAL_BUILD_TESTING_BIGFUZZ=ON
ninja --verbose
ninja test

cd ..
rmdir %BDIR% /s /q
